"""Human-readable display names for secret scanner rule IDs."""

SECRET_TYPE_NAMES = {
    # --- Bundled secrets.toml patterns ---
    "openrouter-api-key": "OpenRouter API Key",
    "openai-api-key": "OpenAI API Key",
    "openai-project-key": "OpenAI Project Key",
    "github-personal-token": "GitHub Personal Token",
    "github-oauth-token": "GitHub OAuth Token",
    "github-refresh-token": "GitHub Refresh Token",
    "github-secret-token": "GitHub Secret Token",
    "anthropic-api-key": "Anthropic API Key",
    "gitlab-personal-token": "GitLab Personal Token",
    "slack-token": "Slack Token",
    "aws-access-key": "AWS Access Key",
    "aws-secret-key": "AWS Secret Key",
    "google-oauth-token": "Google OAuth Token",
    "google-api-key": "Google API Key",
    "azure-client-secret": "Azure Client Secret",
    "npm-token": "npm Token",
    "pypi-token": "PyPI Token",
    "stripe-secret-key": "Stripe Secret Key",
    "stripe-test-secret-key": "Stripe Test Secret Key",
    "stripe-public-key": "Stripe Public Key",
    "stripe-test-public-key": "Stripe Test Public Key",
    "stripe-restricted-key": "Stripe Restricted Key",
    "stripe-test-restricted-key": "Stripe Test Restricted Key",
    "twilio-api-key": "Twilio API Key",
    "sendgrid-api-key": "SendGrid API Key",
    "mailgun-api-key": "Mailgun API Key",
    "square-oauth-secret": "Square OAuth Secret",
    "paypal-braintree-token": "PayPal/Braintree Access Token",
    "paypal-client-secret": "PayPal Client Secret",
    "private-key": "Private Key",
    "env-variable": "Environment Variable",
    "exported-env-variable": "Exported Environment Variable",
    "json-api-key": "JSON API Key",
    "json-token": "JSON Token",
    "json-password": "JSON Password",
    "json-secret": "JSON Secret",
    "yaml-password": "YAML Password",
    "bearer-token": "Bearer Token",
    "api-key-header": "API Key Header",
    "auth-token-header": "Auth Token Header",
    "mongodb-connection": "MongoDB Connection String",
    "mysql-connection": "MySQL Connection String",
    "postgres-connection": "PostgreSQL Connection String",
    "redis-connection": "Redis Connection String",
    "circleci-api-token": "CircleCI API Token",
    "jenkins-api-token": "Jenkins API Token",
    "mongodb-atlas-api-key": "MongoDB Atlas API Key",
    "supabase-service-role-key": "Supabase Service/Anon Key",
    "replicate-api-token": "Replicate API Token",
    "hex-secret-with-context": "Hex Secret",
    "very-long-hex-secret": "Long Hex Secret",
    "base64-secret-with-context": "Base64 Secret",
    "very-long-base64-secret": "Long Base64 Secret",
    # --- Bundled pii.toml patterns ---
    "pii-ssn": "Social Security Number (SSN)",
    "pii-credit-card": "Credit Card Number",
    "pii-us-phone": "US Phone Number",
    "pii-email": "Email Address",
    "pii-us-passport": "US Passport Number",
    "pii-iban": "IBAN Number",
    "pii-intl-phone": "International Phone Number",
    "pii-medical-id": "Medical Record Number",
    "pii-passport": "Passport Number",
    "pii-canada-sin": "Canadian Social Insurance Number",
    # --- Common Gitleaks built-in rule IDs ---
    "generic-api-key": "Generic API Key",
    "github-pat": "GitHub Personal Access Token",
    "github-fine-grained-pat": "GitHub Fine-Grained PAT",
    "github-app-token": "GitHub App Token",
    "gitlab-pat": "GitLab Personal Access Token",
    "gitlab-ptt": "GitLab Pipeline Trigger Token",
    "gitlab-rrt": "GitLab Runner Registration Token",
    "aws-access-token": "AWS Access Token",
    "slack-bot-token": "Slack Bot Token",
    "slack-user-token": "Slack User Token",
    "slack-app-token": "Slack App Token",
    "slack-webhook-url": "Slack Webhook URL",
    "discord-bot-token": "Discord Bot Token",
    "discord-client-secret": "Discord Client Secret",
    "heroku-api-key": "Heroku API Key",
    "digitalocean-pat": "DigitalOcean Personal Access Token",
    "databricks-api-token": "Databricks API Token",
    "shopify-access-token": "Shopify Access Token",
    "hashicorp-tf-api-token": "HashiCorp Terraform API Token",
    "vault-batch-token": "HashiCorp Vault Token",
    "vault-service-token": "HashiCorp Vault Token",
    "hashicorp-vault-token": "HashiCorp Vault Token",
    "doppler-api-token": "Doppler API Token",
    "linear-api-key": "Linear API Key",
    "postman-api-token": "Postman API Token",
    "confluent-secret-key": "Confluent Secret Key",
    "confluent-cloud-api-key": "Confluent Cloud API Key",
    "datadog-access-token": "Datadog Access Token",
    "new-relic-user-api-key": "New Relic User API Key",
    "new-relic-browser-api-token": "New Relic Browser API Token",
    "google-gemini-auth-key": "Google Gemini Auth Key",
    "gcp-api-key": "Google Cloud API Key",
    "telegram-bot-api-token": "Telegram Bot API Token",
    "huggingface-access-token": "Hugging Face Access Token",
    "age-secret-key": "age Secret Key",
}


def get_secret_type_display(rule_id: str) -> str:
    """Return a human-readable name for a scanner rule_id.

    Falls back to title-casing the rule_id itself if no mapping exists.
    """
    if not rule_id or rule_id == "Unknown":
        return "Unknown"
    return SECRET_TYPE_NAMES.get(rule_id, rule_id.replace("-", " ").title())
